### ISSUE TITLE
Some cytrus

### ISSUE THREAD

**Issue by GreyXor** [dofera/cytrus#3]
Lot of cytrus.json since Feb 2022
[cytruses.zip](https://github.com/user-attachments/files/16119419/cytruses.zip)

![image](https://github.com/dofera/cytrus/assets/79602273/2f844cb1-5f36-4a7f-aac9-d6202220eedc)
![image](https://github.com/dofera/cytrus/assets/79602273/a281b3c0-2644-4329-9fb6-c800dbd8f4db)

**Comment by dofera** [comment]
Thank you for your contribution!
